### ISSUE TITLE
Make the icons cacheable

### ISSUE THREAD

**Issue by davidsneighbour** [UtkarshVerma/hugo-mod-svg-icon-system#2]
It should be possible to cache the icons via {{< partialCached "layout" "iconname" "iconname" >}}. Good for re-use of icons.

**Comment by UtkarshVerma** [comment]
Hmm, seems reasonable. I'll implement this.

**Comment by UtkarshVerma** [comment]
This feature has now been implemented. Feel free to reopen this issue if anything is missing.
